import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navigation from '../components/ui/navigation';
import Footer from "@/components/ui/footer"
const poppins = Poppins({ weight: "300", subsets: [] }); 


export const metadata: Metadata = {
  title: "CS50xNepal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navigation/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
